name: Changelog

on:
  pull_request:
    branches:
      - master
      - zowe-v1-lts
      - next

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: ${{ contains( github.event.pull_request.labels.*.name, 'no-changelog') != true }}

    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        fetch-depth: 0

    - name: Check Changelog Updated
      uses: awharn/check_changelog_action@395a530f6f4cf69c60f6d18d6b445d7b37f69823 # v1.1.2
      with:
        header: '## Recent Changes'
        file: 'CHANGELOG.md'
        lerna: true
        ignoreFiles: '__tests__|package.json|package-lock.json|*.md'
